[versions]
agp = "8.6.1"

[libraries]
cxx = { module = "org.lsposed.libcxx:libcxx", version = "27.0.12077973" }

[plugins]
agp-app = { id = "com.android.application", version.ref = "agp" }
lsplugin-cmaker = { id = "org.lsposed.lsplugin.cmaker", version = "1.2" }
